#!/bin/bash
#------------------------------------------------
# require: crontab 
# target : generate crontab script
# author : junjiemars@gmail.com
#------------------------------------------------


OPT_DEP="${OPT_DEP:-$(cd `dirname ${BASH_SOURCE[0]}`; pwd -P)}"
OPT_RUN="${OPT_RUN:-${OPT_DEP}/run}"
CRONTAB_LIST="crontab.list"
W3="${W3:-$OPT_RUN/www}"
VER="${VER:-8.5.16}"


cat << END > "${OPT_DEP%/}/${CRONTAB_LIST}"
# generated by crontab-env.sh

SHELL=`which bash`
PATH=${OPT_DEP%/}${PATH:+:$PATH}
W3=${W3%/}
VER=$VER

# crontab list
# *minute(0-59) *hour(0-23) *day-of-month(1-31) *month(1-12) *day-of-week(0-7)


# * * * * * <job> >> /tmp/x.log 2>&1


END
