#!/bin/bash
#------------------------------------------------
# target: bash env setup script	
# author: junjiemars@gmail.com
#------------------------------------------------

HOME=${HOME%/}
PLATFORM=`uname -s 2>/dev/null`
GITHUB_H="${GITHUB_H:-https://raw.githubusercontent.com/junjiemars/kit/master}"
curl='curl -sL '
declare -a BASH_S=(\
	'.bash_init' \
  '.bash_aliases' \
  '.bash_vars' \
  '.bash_paths' \
  '.bashrc' \
  '.profile' \
  '.bash_profile' \
  '.bash_logout' \
  '.vimrc' \
  '_vimrc' \
  )

save_as() {
  local f="$HOME/$1"
	local ori=$f.ori
  case "${PLATFORM}" in
    MSYS_NT*|MINGW*) 
      local find='/usr/bin/find' 
      local sort='/usr/bin/sort'
      ;;
    *) 
      local find='find' 
      local sort='sort'
      ;;
  esac

  if [ -f ${f} ]; then
		[ -f ${ori} ] || cp $f $ori
    local l=`$find $HOME -maxdepth 1 -mindepth 1 -type f -name "$1.b?" \
            |$sort -r|head -n1`
    if [ "_${l}" == "_" ]; then
      local n=0
    else
      local c="${l:$(( ${#l}-1 )):1}"
      local n=$(( ${c}+1 ))
      if [[ ${n} -gt 2 ]]; then
        let n=0
        [ -f "${f}.b1" ] && mv "${f}.b1" "${f}.b2"
        [ -f "${f}.b0" ] && mv "${f}.b0" "${f}.b1"
      fi
    fi
    cp "${f}" "${f}.b${n}"
  fi
}

to_posix_path() {
  echo "\\$@" | \
    sed -e 's#^\\\([a-zA-Z]\):\\#\\\l\1\\#' | \
    sed -e 's#\\#\/#g' | \
    sed -e 's# #\ #g'
}

set_vim_path_var() {
  local f=$1
  shift
  local inc_lns=("${@}")
  local inc_ln="${#inc_lns[@]}"
  local cc_header="\" cc include path :check_cc_include"
  local t=0

  if [ -f "$f" ]; then
    local line_no=`grep -m1 -n "^${cc_header}" $f | cut -d':' -f1`
    t=$?
    if [ 0 -eq $t -a $line_no -gt 0 ]; then
      sed -i.pre -e "$line_no,\$d" $f
    fi
  fi

  echo -e "\n${cc_header}" >> $f
  for i in "${inc_lns[@]}"; do
		local ln=$(echo "$i" | sed 's_ _\\\\\\ _g')
    echo "set path+=${ln}" >> $f
  done
}

check_linux_cc_include() {
	local inc_list=$1
	local vimrc=$2
  if `type -p cc &>/dev/null`; then
    local cc_out="`echo '' | cc -v -E 2>&1 >/dev/null - \
									| awk '/#include <...> search starts here:/,/End of search list./'`"
    [ -n "$cc_out" ] || return 1

		local inc_lns=()
		IFS=$'\n'
		for l in `echo "$cc_out"`; do
			inc_lns+=($(echo "$l" | sed 's/^ //'))
		done
		unset IFS

		cat /dev/null > "$inc_list"
		local inc_ln="${#inc_lns[@]}"
		if [[ 2 -lt "$inc_ln" ]]; then
			local inc_paths=("${inc_lns[@]:1:$(( inc_ln-2  ))}")
			echo "${inc_paths[@]}" >> "$inc_list"
			set_vim_path_var "${vimrc}" "${inc_paths[@]}"
    fi
  fi
}

find_vctools() {
 	local vstools="`env|grep 'VS[0-9][0-9]*COMNTOOLS'|sed 's#^VS[0-9]*COMNTOOLS=\(.*\)$#\1#g'`"

  if [ -n "$vstools" ]; then
    vstools="`( cd "$vstools/../../VC" && pwd )`"
    vstools="`echo "$vstools" | sed -e 's#^\/\([a-z]\)#\u\1:#'`"
    if [ -d "$vstools" ]; then
      echo "$vstools"
      return 0
    fi
  fi

  local vswhere="`to_posix_path \"${PROGRAMFILES} (x86)/Microsoft Visual Studio/Installer/vswhere.exe\"`"
  if [ -f "${vswhere}" ]; then
    vstools="`cd \"$(dirname \"${vswhere}\")\"; ./vswhere.exe -latest -property installationPath`"
    if [ -n "$vstools" ]; then
      vstools="${vstools}\VC\Auxiliary\Build"
      if [ -d "$vstools" ]; then
        echo "$vstools"
        return 0
      fi
    fi
  fi

  return 1
}

check_win_cc_include() {
	local inc_list="$1"
  local vimrc="$2"
  local inc_bat="$3"

	local vstools="`find_vctools`"
	[ -n "$vstools" ] || return 0

  cat <<END > "$inc_bat"
@echo off
REM %userprofile%/.vc-inc.bat
REM generated by Nore (https://github.com/junjiemars/nore)
set wpwd=%cd%
cd /d "$vstools"
if "%1" == "" goto :x86
if "%1" == "x86" goto :x86
if "%1" == "x86_arm" goto :x86
if "%1" == "x64" goto :x86_64
if "%1" == "x86_amd64" goto :x86_64

:x86
call vcvarsall.bat x86
set CC=cl
set AS=ml
goto :echo_inc

:x86_64
call vcvarsall.bat %*
set CC=cl
set AS=ml64
goto :echo_inc

:echo_inc
cd /d %wpwd%
echo "%INCLUDE%" 
END

	[ -f "$inc_bat" ] || return 1
	chmod u+x "$inc_bat"

 	local include=$($inc_bat) 
	[ -n "$include" ] || return 1

	cat /dev/null > "$inc_list"
 	include=$(echo $include | sed 's#\"##g')
 	local inc_lns=()
 	IFS=$';'
 	for i in `echo "${include}"`; do
		local ln=$(echo "\\${i}"|sed -e 's#^\\\([a-zA-Z]\):\\#\\\l\1\\#' -e 's#\\#\/#g')
		echo "'$ln'" >> "$inc_list"
		inc_lns+=( "$ln" )
 	done
 	unset IFS

 	set_vim_path_var "${vimrc}" "${inc_lns[@]}"
}

function delete_tail_line() {
	local os="$1" 
	local r="$2"
	local f="$3"

	sed_i_0="-i''"
	[ "Darwin" = "$os" ] && sed_i_0="-i ''"
	if [ -f "$f" ]; then
		if `tail -n1 $f | grep "$r" &>/dev/null`; then
			sed $sed_i_0 -e '$d' "$f"
		fi
	fi
}



BEGIN=`date +%s`
echo "setup $PLATFORM bash env ..."

for i in "${BASH_S[@]}"; do
  `save_as "$i"`
done

${curl} ${GITHUB_H}/ul/.bash_aliases -o $HOME/.bash_aliases
${curl} ${GITHUB_H}/ul/.bash_vars -o $HOME/.bash_vars
${curl} ${GITHUB_H}/ul/.bash_paths -o $HOME/.bash_paths
${curl} ${GITHUB_H}/ul/.bash_profile -o $HOME/.bash_profile

case ${PLATFORM} in
  MSYS_NT*|MINGW*)
    ${curl} ${GITHUB_H}/win/.bashrc -o $HOME/.bashrc
    ${curl} ${GITHUB_H}/ul/.vimrc -o $HOME/_vimrc && \
      cp $HOME/_vimrc $HOME/.vimrc
    ;;
  *)
		sed_i_0="-i''"
		[ "Darwin" = "$PLATFORM" ] && sed_i_0="-i ''"
		${curl} ${GITHUB_H}/ul/.bashrc -o $HOME/.bash_init
		
		delete_tail_line "`uname -s 2>/dev/null`" 'LD_LIBRARY_PATH' "$HOME/.bashrc" 
		delete_tail_line "`uname -s 2>/dev/null`" 'export\ * PATH' "$HOME/.bashrc" 
		delete_tail_line "`uname -s 2>/dev/null`" 'test -f.*\.bash_init' "$HOME/.bashrc" 

		cat << END >> $HOME/.bashrc
test -f \${HOME%/}/.bash_init && . \${HOME%/}/.bash_init
export PATH
export LD_LIBRARY_PATH
END
    ${curl} ${GITHUB_H}/ul/.bash_logout -o $HOME/.bash_logout
    ${curl} ${GITHUB_H}/ul/.vimrc -o $HOME/.vimrc
    ;;
esac

. $HOME/.bashrc

case ${PLATFORM} in
  Linux)
    check_linux_cc_include $HOME/.cc-inc.list $HOME/.vimrc
    ;;
  MSYS_NT*|MINGW*)
    check_win_cc_include $HOME/.cc-inc.list $HOME/.vimrc $HOME/.vc-inc.bat
    ;;
  *)
    ;;
esac

END=`date +%s`
echo 
echo "... elpased $(( ${END}-${BEGIN} )) seconds, successed."

