version: '2.0'

services:
  centos-dev:
    image: junjiemars/centos-dev:latest
    container_name: bone-centos-dev
    hostname: centos
    # privileged: true
    working_dir: /home/u
    environment:
      - INSIDE_DOCKER=1
    ports:
      - 9601:9601
