version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch-dev
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      -  ingest.geoip.downloader.enabled=false
      # - ELASTIC_USERNAME=elastic
      # - ELASTIC_PASSWORD=B4iwoicWLDWHFCV6T_AB
      - xpack.security.enabled=false
      # - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    # networks:
    #   - elastic
volumes:
  elasticsearch_data:
    # driver: local
# networks:
#   elastic:
#     driver: bridge
