version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch-dev
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
    # networks:
    #   - elastic
volumes:
  es_data:
    # driver: local
# networks:
#   elastic:
#     driver: bridge
