version: '2.0'

services:
  java-openjdk-dev:
    image: junjiemars/java-openjdk-dev:latest
    container_name: bone-java-openjdk-dev
    hostname: openjdk
    privileged: true
    working_dir: /home/u
    environment:
      - INSIDE_DOCKER=1
      - SHELL=/bin/bash
    volumes:
      - ${OPT_OPEN}:/opt/open
    ports:
      - 9701:9701
