version: "3"

# podman machine ssh

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-dev
    restart: on-failure
    logging:
      driver: k8s-file
    volumens:
      - jenkins-data:/var/jenkins_home
    ports:
      - "9080:8080"
      - "9082:50000"

volumes:
  jenkins-data:
