version: "3"

# podman machine ssh

services:
  sonarqube:
    image: jenkins/jenkins:lts
    container_name: jenkins-dev
    logging:
      driver: none
    volumens:
      - jenkins-data:/var/jenkins_home
    ports:
      - "9080:8080"
      - "9082:50000"

volumes:
  jenkins-data:
