version: "3"

services:
  jupyter:
    image: jupyter/datascience-notebook
    # image: jupyter/minimal-notebook
    container_name: jupyter-dev
    logging:
      driver: k8s-file
    volumes:
      - jupyter_work:/home/jovyan/work
    ports:
      - 8888:8888
      
volumes:
  jupyter_work:
