version: "3"

services:
  jupyter:
    image: jupyter/datascience-notebook
    # image: jupyter/minimal-notebook
    container_name: jupyter-dev
    environment:
      PIP_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
    logging:
      driver: k8s-file
    resources:
      limits:
        cpu: 0.2
    volumes:
      - jupyter_work:/home/jovyan/work
    ports:
      - 8888:8888
      
volumes:
  jupyter_work:
