version: '2.0'

services:
  db:
    image: mysql
    container_name: mysql-dev
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  # adminer:
  #   image: adminer
  #   container_name: adminer-dev
  #   restart: always
  #   ports:
  #     - 8080:8080


