version: '3.0'

# https://github.com/docker-library/nginx/blob/master/
# sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80

services:
  redis:
    image: nginx
    container_name: nginx-dev
    restart: on-failure
    ports:
      - 80:80
      - 443:443


