version: '3'
# https://github.com/gvenzl/oci-oracle-xe

services:
  db:
    image: gvenzl/oracle-xe:11
    container_name: oci-oracle-xe-db
    environment:
      ORACLE_PASSWORD=example
    resources:
      limits:
        cpu: 0.2
    volumes:
      oracle_volume:/u01/app/oracle/oradata
    ports:
      - 1521:1521
      - 127.0.0.1:9090:8080

volumes:
  oracle_volume:

# http://127.0.0.1:9090/apex
# system/oracle
# podman exec oci-oracle-xe-db resetPassword example 
