version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    restart: always
    ports:
      - "5672:5672"      # RabbitMQ default port
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user         # Default username
      RABBITMQ_DEFAULT_PASS: password     # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   # Persist RabbitMQ data

volumes:
  rabbitmq_data:
