version: '3.0'

# https://github.com/docker-library/redis/blob/master/README.md

services:
  redis:
    image: redis:6
    container_name: redis-dev
    restart: on-failure
    ports:
      - 6379:6379
