version: "3"

# podman machine ssh
# sysctl -w vm.max_map_count=524288
# sysctl -w fs.file-max=131072
# admin/admin
# admin/admin123

services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-dev
    # sysctls:
    #   - vm.max_map_count=524288
    #   - fs.file-max=131072
    ulimits:
      nofile: 131072
      nproc: 8192
    depends_on:
      - db
    environment:
      SONAR_SEARCH_JAVAADDITIONALOPTS: -Ddiscovery.type='single-node' -Dnode.store.allow_mmap=false
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    logging:
      driver: k8s-file
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    container_name: sonarqube-postgres-dev
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
