version: "3"

# https://github.com/docker-library/tomcat/blob/master/README.md

services:
  tomcat:
    image: tomcat:10
    # image: tomcat:8-jre8
    container_name: tomcat-dev
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    command: "catalina.sh run"
    logging:
      driver: k8s-file
    volumes:
      - tomcat_root:/usr/local/tomcat
    ports:
      - 9080:8080
      - 9085:5005

volumes:
  tomcat_root:
