version: "3"

# https://github.com/docker-library/tomcat/blob/master/README.md

services:
  tomcat:
    # image: tomcat:10
    image: tomcat:8-jdk8
    container_name: tomcat-dev
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005"
    command: "catalina.sh run"
    logging:
      driver: k8s-file
    volumes:
      - tomcat_root:/usr/local/tomcat
    ports:
      - 8080:8080
      - 5005:5005
  #   depends_on:
  #     - redis
  # redis:
  #   image: redis:6
  #   container_name: redis-dev
  #   command: redis-server --requirepass 'XXX'
  #   restart: on-failure
  #   ports:
  #     - 6379:6379
      
volumes:
  tomcat_root:
