version: "3"

services:
  tomcat:
    image: tomcat:8
    container_name: tomcat-dev
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    logging:
      driver: k8s-file
    # command: "catalina.sh run"
    volumes:
      - tomcat_root:/usr/local/tomcat
    ports:
      - 9080:8080
      - 9085:5005

volumes:
  tomcat_root:
